import {NextResponse} from "next/server";
import {getSession,isAdmin} from "@/lib/auth";
import {initDb,pool} from "@/lib/db";
import {audit,requestIp} from "@/lib/audit";

export async function GET(req:Request){
 if(!await isAdmin())return NextResponse.json({error:"Acesso administrativo obrigatório."},{status:401});await initDb();const url=new URL(req.url),exportType=url.searchParams.get("export");
 if(exportType){let rows:unknown[]=[];if(exportType==="users")({rows}=await pool.query("SELECT id,name,email,status,created_at,updated_at,last_seen FROM users WHERE id<>'admin' ORDER BY created_at"));else if(exportType==="leagues")({rows}=await pool.query("SELECT id,code,country,name,season,file_name,games,updated_at,data_quality FROM leagues ORDER BY country,name"));else if(exportType==="history")({rows}=await pool.query("SELECT id,user_id,mode,league_id,home,away,market,confidence,result_status,result_note,component_results,resolution_source,matched_game,created_at,resolved_at FROM analysis_history ORDER BY created_at"));else return NextResponse.json({error:"Exportação inválida."},{status:400});await audit("data_exported",await getSession(),"export",exportType,{records:rows.length},requestIp(req));return new NextResponse(JSON.stringify({exportedAt:new Date().toISOString(),type:exportType,records:rows},null,2),{headers:{"Content-Type":"application/json; charset=utf-8","Content-Disposition":`attachment; filename="alves-v12-${exportType}-${new Date().toISOString().slice(0,10)}.json"`}})}
 const [users,leagues,history,pending,audits,failures,settings]=await Promise.all([pool.query("SELECT count(*)::int n FROM users WHERE id<>'admin'"),pool.query("SELECT count(*)::int n FROM leagues"),pool.query("SELECT count(*)::int n FROM analysis_history"),pool.query("SELECT count(*)::int n FROM analysis_history WHERE result_status='pending'"),pool.query("SELECT id,actor_id,actor_role,action,target_type,target_id,details,ip,created_at FROM audit_logs ORDER BY created_at DESC LIMIT 80"),pool.query("SELECT count(*)::int n FROM login_attempts WHERE success=false AND created_at>$1",[Date.now()-24*60*60*1000]),pool.query("SELECT key,value,updated_at,updated_by FROM system_settings ORDER BY key")]);
 return NextResponse.json({health:{database:true,sessionSecret:!!process.env.SESSION_SECRET,adminEnvironment:!!(process.env.ADMIN_USER&&process.env.ADMIN_PASSWORD_HASH),footballApi:!!process.env.FOOTBALL_DATA_TOKEN,ai:!!process.env.OPENROUTER_API_KEY},counts:{users:users.rows[0].n,leagues:leagues.rows[0].n,history:history.rows[0].n,pending:pending.rows[0].n,failedLogins24h:failures.rows[0].n},settings:Object.fromEntries(settings.rows.map(x=>[x.key,x.value])),audits:audits.rows});
}

export async function PATCH(req:Request){
 if(!await isAdmin())return NextResponse.json({error:"Acesso administrativo obrigatório."},{status:401});const actor=await getSession(),b=await req.json(),key=String(b.key||"");if(!["settlement_rules","bot_defaults"].includes(key))return NextResponse.json({error:"Configuração inválida."},{status:400});let value=b.value||{};if(key==="settlement_rules")value={yellowWeight:Math.max(0,Math.min(3,Number(value.yellowWeight??1))),redWeight:Math.max(0,Math.min(5,Number(value.redWeight??1))),includeExtraTime:value.includeExtraTime===true,autoGoals:value.autoGoals!==false,autoCorners:value.autoCorners!==false,autoCards:value.autoCards===true,batchSize:Math.max(20,Math.min(500,Number(value.batchSize||200)))};if(key==="bot_defaults")value={minConfidence:Math.max(60,Math.min(90,Number(value.minConfidence||65))),minGames:Math.max(3,Math.min(20,Number(value.minGames||5))),oddReminder:String(value.oddReminder||"1,62 a 1,80").slice(0,30)};await initDb();await pool.query("INSERT INTO system_settings(key,value,updated_at,updated_by) VALUES($1,$2::jsonb,$3,$4) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=EXCLUDED.updated_at,updated_by=EXCLUDED.updated_by",[key,JSON.stringify(value),Date.now(),actor?.id||"admin"]);await audit("system_settings_changed",actor,"setting",key,{value},requestIp(req));return NextResponse.json({ok:true,value});
}
