"use client";
import {useEffect,useMemo,useState} from "react";
type Summary={total:number;hits:number;misses:number;pending:number;resolved:number;accuracy:number;minSample:number;sampleReady:boolean};
type Group={name:string;total:number;hits:number;misses:number;resolved:number;accuracy:number};
type Recent={total:number;hits:number;misses:number;accuracy:number};
type Month=Recent&{key:string;label:string;pending:number};
type Item={id:string;mode:string;home:string;away:string;market:string;confidence:number;result_status:"pending"|"hit"|"miss";result_note:string;created_at:number;user_name:string;league_name?:string;resolution_source?:string;component_results?:{market:string;status:"hit"|"miss"|"unavailable";actual?:number;reason:string}[]};
type Data={summary:Summary;trend:{days7:Recent;days30:Recent};monthly:Month[];cumulative:{index:number;value:number;status:string}[];byLeague:Group[];byMarket:Group[];byLine:Group[];byDirection:Group[];byMode:Group[];highlights:{bestLeague?:Group;bestMarket?:Group;worstMarket?:Group;bestLine?:Group;bestDirection?:Group};insights:string[];items:Item[]};
const empty:Data={summary:{total:0,hits:0,misses:0,pending:0,resolved:0,accuracy:0,minSample:10,sampleReady:false},trend:{days7:{total:0,hits:0,misses:0,accuracy:0},days30:{total:0,hits:0,misses:0,accuracy:0}},monthly:[],cumulative:[],byLeague:[],byMarket:[],byLine:[],byDirection:[],byMode:[],highlights:{},insights:[],items:[]};

function Table({title,rows,limit=8}:{title:string;rows:Group[];limit?:number}){return <article><h4>{title}</h4>{!rows.length&&<p className="performance-empty">Ainda não há dados.</p>}{rows.slice(0,limit).map(x=><div key={x.name}><span>{x.name}<small>{x.resolved} confirmadas • {x.total} registros</small></span><b className={x.resolved<10?'sample-small':x.accuracy>=60?'result-hit':x.accuracy<50?'result-miss':''}>{x.resolved?`${x.accuracy}%`:"Aguardando"}</b></div>)}</article>}
function Evolution({points}:{points:Data["cumulative"]}){const path=useMemo(()=>{if(!points.length)return "";const vals=points.map(x=>x.value),min=Math.min(...vals,0),max=Math.max(...vals,0),range=Math.max(1,max-min);return points.map((p,i)=>`${i?'L':'M'} ${points.length===1?50:(i/(points.length-1))*100} ${90-((p.value-min)/range)*75}`).join(' ')},[points]);return <div className="performance-chart"><div className="chart-title"><span><b>Evolução das confirmações</b><small>Acerto soma 1 • erro subtrai 1</small></span><strong>{points.at(-1)?.value||0}</strong></div>{path?<svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Evolução acumulada de acertos e erros"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#32e795" stopOpacity=".35"/><stop offset="1" stopColor="#32e795" stopOpacity="0"/></linearGradient></defs><path d={`${path} L 100 100 L 0 100 Z`} fill="url(#area)"/><path d={path} fill="none" stroke="#32e795" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>:<p className="performance-empty">Confirme resultados para formar o gráfico.</p>}</div>}

export default function AdminPerformance(){
 const [data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[question,setQuestion]=useState(""),[answer,setAnswer]=useState("Selecione uma pergunta ou escreva o que deseja saber sobre o histórico confirmado.");
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/performance',{cache:'no-store'}),d=await r.json();if(r.ok)setData(d);else setMessage(d.error||'Não foi possível carregar.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const resolve=async(id:string,status:'pending'|'hit'|'miss')=>{const note=status==='pending'?"":prompt('Observação opcional sobre o resultado:')||"";const r=await fetch('/api/admin/performance',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status,note})});if(r.ok){setMessage(status==='hit'?'Análise marcada como acerto.':status==='miss'?'Análise marcada como erro.':'Análise devolvida para aguardando.');load()}};
 const remove=async(id:string)=>{if(!confirm('Excluir permanentemente este registro de análise?'))return;const r=await fetch(`/api/admin/performance?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(r.ok)load()};
 const autoCheck=async()=>{setLoading(true);try{const r=await fetch('/api/admin/performance',{method:'POST'}),d=await r.json();if(r.ok){setMessage(`${d.settled} previsão(ões) confirmadas automaticamente; ${d.partial} com resultado parcial.`);await load()}else setMessage(d.error||'Não foi possível conferir os resultados.')}finally{setLoading(false)}};
 const ask=(value=question)=>{const q=value.toLocaleLowerCase('pt-BR'),{summary,highlights}=data;if(!summary.sampleReady){setAnswer(`Ainda existem somente ${summary.resolved} resultados confirmados. Para uma conclusão mais segura, confirme pelo menos ${summary.minSample}.`);return}if(/pior|evitar|erro|negativ/.test(q)){const x=highlights.worstMarket;setAnswer(x?`${x.name} tem o desempenho mais baixo entre os mercados com amostra mínima: ${x.accuracy}% em ${x.resolved} resultados. Isso é um alerta para revisar os critérios, não uma ordem de aposta.`:'Ainda não existe mercado com amostra mínima suficiente.');return}if(/linha/.test(q)){const x=highlights.bestLine;setAnswer(x?`${x.name} é a linha com melhor histórico elegível: ${x.accuracy}% em ${x.resolved} confirmações.`:'Ainda não há uma linha com 10 resultados confirmados.');return}if(/liga|campeonato/.test(q)){const x=highlights.bestLeague;setAnswer(x?`${x.name} apresenta o melhor histórico entre as ligas elegíveis: ${x.accuracy}% em ${x.resolved} confirmações.`:'Ainda não há uma liga com amostra mínima.');return}if(/mais|menos|over|under/.test(q)){const x=highlights.bestDirection;setAnswer(x?`${x.name} tem o melhor resultado histórico: ${x.accuracy}% em ${x.resolved} confirmações. Compare também as linhas individuais antes de concluir.`:'Ainda não existe amostra mínima para comparar Mais e Menos.');return}const x=highlights.bestMarket;setAnswer(`A taxa geral é ${summary.accuracy}% em ${summary.resolved} resultados confirmados.${x?` O melhor mercado elegível é ${x.name}, com ${x.accuracy}%.`:''} Previsões aguardando não entram nesse cálculo.`)};
 const suggested=["Qual é meu melhor mercado?","Qual linha funciona melhor?","É melhor Mais ou Menos?","Qual mercado devo revisar?"];
 return <section className="panel performance-admin"><div className="panel-head"><i className="green">✓</i><div><h3>Analista de desempenho das previsões</h3><p>Área exclusiva do administrador • análise gratuita do histórico real salvo</p></div><div className="performance-head-actions"><button onClick={autoCheck} disabled={loading}>✓ Conferir resultados</button><button onClick={load} disabled={loading}>{loading?'Carregando...':'↻ Atualizar'}</button></div></div>
  <div className={`sample-banner ${data.summary.sampleReady?'ready':''}`}><span><b>{data.summary.sampleReady?'Amostra mínima alcançada':'Construindo amostra estatística'}</b><small>{data.summary.resolved} de pelo menos {data.summary.minSample} resultados confirmados</small></span><progress max={data.summary.minSample} value={Math.min(data.summary.resolved,data.summary.minSample)}/></div>
  <div className="performance-kpis"><article><small>TAXA REAL</small><b>{data.summary.accuracy}%</b><span>{data.summary.resolved} conferidas</span></article><article><small>ACERTOS</small><b>{data.summary.hits}</b><span>resultados confirmados</span></article><article><small>ERROS</small><b>{data.summary.misses}</b><span>resultados confirmados</span></article><article><small>AGUARDANDO</small><b>{data.summary.pending}</b><span>precisam de resultado</span></article><article><small>MELHOR MERCADO</small><b>{data.highlights.bestMarket?.name||'—'}</b><span>{data.highlights.bestMarket?`${data.highlights.bestMarket.accuracy}% • amostra válida`:'Aguardando amostra mínima'}</span></article><article><small>MELHOR LINHA</small><b>{data.highlights.bestLine?.name||'—'}</b><span>{data.highlights.bestLine?`${data.highlights.bestLine.accuracy}% • amostra válida`:'Aguardando amostra mínima'}</span></article></div>
  <div className="performance-visuals"><Evolution points={data.cumulative}/><div className="outcome-card"><div className="donut" style={{background:`conic-gradient(#32e795 0 ${data.summary.accuracy}%,#ff596d ${data.summary.accuracy}% 100%)`}}><span><b>{data.summary.accuracy}%</b><small>ACERTOS</small></span></div><div><b>Distribuição confirmada</b><span><i className="hit-dot"/> {data.summary.hits} acertos</span><span><i className="miss-dot"/> {data.summary.misses} erros</span><small>Sem odds e valores registrados, o painel não inventa lucro ou ROI.</small></div></div></div>
  <div className="monthly-performance"><h4>Desempenho mês a mês</h4><div>{data.monthly.map(x=><article key={x.key} className={x.total?'active':''}><small>{x.label}</small><b>{x.hits+x.misses?`${x.accuracy}%`:'—'}</b><span>{x.hits}A • {x.misses}E</span></article>)}</div></div>
  <div className="performance-recent"><article><small>ÚLTIMOS 7 DIAS</small><b>{data.trend.days7.accuracy}%</b><span>{data.trend.days7.hits+data.trend.days7.misses} conferidas • {data.trend.days7.total} registros</span></article><article><small>ÚLTIMOS 30 DIAS</small><b>{data.trend.days30.accuracy}%</b><span>{data.trend.days30.hits+data.trend.days30.misses} conferidas • {data.trend.days30.total} registros</span></article></div>
  <div className="performance-groups"><Table title="Desempenho por liga" rows={data.byLeague}/><Table title="Desempenho por mercado" rows={data.byMarket}/><Table title="Comparação Mais × Menos" rows={data.byDirection}/><Table title="Desempenho por linha" rows={data.byLine} limit={12}/><Table title="Origem das análises" rows={data.byMode}/></div>
  <section className="performance-insights"><div><small>LEITURA AUTOMÁTICA DO HISTÓRICO</small><h4>Pontos importantes e alertas</h4></div>{data.insights.map((x,i)=><p key={i}><i>{i+1}</i>{x}</p>)}<span>Conclusões são estatísticas do histórico e não garantem resultados futuros.</span></section>
  {data.items.some(x=>x.component_results?.length)&&<section className="component-performance"><header><small>CONFERÊNCIA MERCADO POR MERCADO</small><h4>O que acertou e o que derrubou cada combinação</h4></header>{data.items.filter(x=>x.component_results?.length).slice(0,12).map(x=><article key={x.id}><div><b>{x.home} × {x.away}</b><small>{x.user_name} • {x.resolution_source||'Conferência manual'}</small></div><section>{x.component_results!.map(c=><span key={c.market} className={`component-${c.status}`}><i>{c.status==='hit'?'✓':c.status==='miss'?'×':'?'}</i><b>{c.market}</b><small>{c.actual===undefined?'Dado indisponível':`Resultado real: ${c.actual}`}</small></span>)}</section></article>)}</section>}
  <section className="performance-chat"><div><small>CONSULTOR ESTATÍSTICO GRATUITO</small><h4>Faça perguntas sobre seus resultados</h4><p>As respostas usam somente os registros confirmados no seu banco de dados.</p></div><div className="chat-suggestions">{suggested.map(x=><button key={x} onClick={()=>{setQuestion(x);ask(x)}}>{x}</button>)}</div><div className="chat-answer"><i>AI</i><p>{answer}</p></div><form onSubmit={e=>{e.preventDefault();ask()}}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ex.: em qual mercado tenho mais erros?"/><button type="submit">Analisar histórico</button></form></section>
  <details className="performance-list"><summary>Ver e conferir todas as previsões ({data.items.length})</summary>{message&&<p className="admin-message">{message}</p>}<div>{data.items.map(x=><article key={x.id}><span><small>{x.mode==='live'?'AO VIVO':x.mode==='prebot'?'BOT PRÉ-LIVE':'PRÉ-JOGO'} • {x.league_name||'Liga não informada'}</small><b>{x.home} × {x.away}</b><em>{x.user_name} • {new Date(Number(x.created_at)).toLocaleString('pt-BR')}</em></span><span><small>{x.mode==='prebot'?'COMBINAÇÃO SALVA':'MERCADO PRINCIPAL'}</small><b>{x.market||'Análise geral'} • {Number(x.confidence||0).toFixed(0)}%</b><em className={`result-${x.result_status}`}>{x.result_status==='hit'?'ACERTO':x.result_status==='miss'?'ERRO':'AGUARDANDO'}</em></span><div><button onClick={()=>resolve(x.id,'hit')}>✓ Acerto</button><button onClick={()=>resolve(x.id,'miss')}>× Erro</button><button onClick={()=>resolve(x.id,'pending')}>↶ Aguardar</button><button className="danger" onClick={()=>remove(x.id)}>Excluir</button></div></article>)}</div></details>
 </section>;
}
