"use client";
import {useEffect,useState} from "react";
type Summary={total:number;hits:number;misses:number;pending:number;accuracy:number};
type Group={name:string;total:number;hits:number;misses:number;accuracy:number};
type Recent={total:number;hits:number;misses:number;accuracy:number};
type Item={id:string;mode:string;home:string;away:string;market:string;confidence:number;result_status:"pending"|"hit"|"miss";result_note:string;created_at:number;user_name:string;league_name?:string};
const empty:Summary={total:0,hits:0,misses:0,pending:0,accuracy:0};
export default function AdminPerformance(){
 const [data,setData]=useState<{summary:Summary;trend:{days7:Recent;days30:Recent};byLeague:Group[];byMarket:Group[];items:Item[]}>({summary:empty,trend:{days7:{total:0,hits:0,misses:0,accuracy:0},days30:{total:0,hits:0,misses:0,accuracy:0}},byLeague:[],byMarket:[],items:[]}),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/performance',{cache:'no-store'}),d=await r.json();if(r.ok)setData(d);else setMessage(d.error||'Não foi possível carregar.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const resolve=async(id:string,status:'pending'|'hit'|'miss')=>{const note=status==='pending'?"":prompt('Observação opcional sobre o resultado:')||"";const r=await fetch('/api/admin/performance',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status,note})});if(r.ok){setMessage(status==='hit'?'Análise marcada como acerto.':status==='miss'?'Análise marcada como erro.':'Análise devolvida para aguardando.');load()}};
 const remove=async(id:string)=>{if(!confirm('Excluir permanentemente este registro de análise?'))return;const r=await fetch(`/api/admin/performance?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(r.ok)load()};
 const bestLeague=data.byLeague.find(x=>x.hits+x.misses>0),bestMarket=data.byMarket.find(x=>x.hits+x.misses>0);
 return <section className="panel performance-admin"><div className="panel-head"><i className="green">✓</i><div><h3>Desempenho comprovado das análises</h3><p>Área exclusiva do administrador • confirme resultados gratuitamente</p></div><button onClick={load} disabled={loading}>{loading?'Carregando...':'↻ Atualizar'}</button></div>
  <div className="performance-kpis"><article><small>TAXA REAL</small><b>{data.summary.accuracy}%</b><span>{data.summary.hits+data.summary.misses} conferidas</span></article><article><small>ACERTOS</small><b>{data.summary.hits}</b><span>resultados confirmados</span></article><article><small>ERROS</small><b>{data.summary.misses}</b><span>resultados confirmados</span></article><article><small>AGUARDANDO</small><b>{data.summary.pending}</b><span>precisam de resultado</span></article><article><small>MELHOR LIGA</small><b>{bestLeague?.name||'—'}</b><span>{bestLeague?`${bestLeague.accuracy}% em ${bestLeague.hits+bestLeague.misses} conferidas`:'Sem amostra'}</span></article><article><small>MELHOR MERCADO</small><b>{bestMarket?.name||'—'}</b><span>{bestMarket?`${bestMarket.accuracy}% em ${bestMarket.hits+bestMarket.misses} conferidas`:'Sem amostra'}</span></article></div>
  <div className="performance-recent"><article><small>ÚLTIMOS 7 DIAS</small><b>{data.trend.days7.accuracy}%</b><span>{data.trend.days7.hits+data.trend.days7.misses} conferidas • {data.trend.days7.total} registros</span></article><article><small>ÚLTIMOS 30 DIAS</small><b>{data.trend.days30.accuracy}%</b><span>{data.trend.days30.hits+data.trend.days30.misses} conferidas • {data.trend.days30.total} registros</span></article></div>
  <div className="performance-groups"><article><h4>Desempenho por liga</h4>{data.byLeague.slice(0,8).map(x=><div key={x.name}><span>{x.name}<small>{x.total} análises</small></span><b>{x.hits+x.misses?`${x.accuracy}%`:'Aguardando'}</b></div>)}</article><article><h4>Desempenho por mercado</h4>{data.byMarket.map(x=><div key={x.name}><span>{x.name}<small>{x.total} análises</small></span><b>{x.hits+x.misses?`${x.accuracy}%`:'Aguardando'}</b></div>)}</article></div>
  <details className="performance-list"><summary>Ver e conferir todas as previsões ({data.items.length})</summary>{message&&<p className="admin-message">{message}</p>}<div>{data.items.map(x=><article key={x.id}><span><small>{x.mode==='live'?'AO VIVO':'PRÉ-JOGO'} • {x.league_name||'Liga não informada'}</small><b>{x.home} × {x.away}</b><em>{x.user_name} • {new Date(Number(x.created_at)).toLocaleString('pt-BR')}</em></span><span><small>MERCADO PRINCIPAL</small><b>{x.market||'Análise geral'} • {Number(x.confidence||0).toFixed(0)}%</b><em className={`result-${x.result_status}`}>{x.result_status==='hit'?'ACERTO':x.result_status==='miss'?'ERRO':'AGUARDANDO'}</em></span><div><button onClick={()=>resolve(x.id,'hit')}>✓ Acerto</button><button onClick={()=>resolve(x.id,'miss')}>× Erro</button><button onClick={()=>resolve(x.id,'pending')}>↶ Aguardar</button><button className="danger" onClick={()=>remove(x.id)}>Excluir</button></div></article>)}</div></details>
 </section>;
}
