import { NextResponse } from "next/server";
import { isAuthorized } from "@/lib/auth";
import { initDb, pool } from "@/lib/db";

const clean=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/conmebol|\b20\d{2}\b/g,"").replace(/[^a-z0-9]/g,"");
const statusMap:Record<string,{short:string;long:string}>={IN_PLAY:{short:"LIVE",long:"Ao vivo"},PAUSED:{short:"HT",long:"Intervalo"},TIMED:{short:"NS",long:"Agendado"},SCHEDULED:{short:"NS",long:"Agendado"},FINISHED:{short:"FT",long:"Encerrado"},POSTPONED:{short:"PST",long:"Adiado"},CANCELLED:{short:"CANC",long:"Cancelado"}};

export async function GET(req:Request){
  if(!(await isAuthorized()))return NextResponse.json({error:"Faça login para acessar."},{status:401});
  const url=new URL(req.url),id=url.searchParams.get("id"),provider=url.searchParams.get("provider"),apiKey=process.env.API_FOOTBALL_KEY,fdToken=process.env.FOOTBALL_DATA_TOKEN;
  if(id&&provider==="football-data")return NextResponse.json({available:true,statistics:[],limited:true,reason:"O plano gratuito do Football-Data.org não fornece estatísticas detalhadas ao vivo."});
  if(id){if(!apiKey)return NextResponse.json({available:false,reason:"API-Football indisponível para estatísticas detalhadas."});try{const r=await fetch(`https://v3.football.api-sports.io/fixtures/statistics?fixture=${encodeURIComponent(id)}`,{headers:{"x-apisports-key":apiKey},next:{revalidate:45}}),d=await r.json(),error=d?.errors&&Object.keys(d.errors).length?String(Object.values(d.errors)[0]):"";return r.ok&&!error?NextResponse.json({available:true,statistics:d.response||[]}):NextResponse.json({available:false,statistics:[],reason:error||"Estatísticas indisponíveis."});}catch{return NextResponse.json({available:false,statistics:[],reason:"Estatísticas indisponíveis."});}}
  await initDb();const {rows}=await pool.query("SELECT id,name,code,country FROM leagues"),registered=rows.map(x=>({id:String(x.id),name:String(x.name),code:String(x.code||"").trim(),country:String(x.country||"")}));
  if(!registered.length)return NextResponse.json({available:true,games:[],reason:"Nenhuma liga foi cadastrada."});
  const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());let primaryReason="";
  if(apiKey)try{let response=await fetch(`https://v3.football.api-sports.io/fixtures?date=${today}&timezone=${encodeURIComponent("America/Sao_Paulo")}`,{headers:{"x-apisports-key":apiKey},next:{revalidate:30}}),data=await response.json(),error=data?.errors&&Object.keys(data.errors).length?String(Object.values(data.errors)[0]):"",fixtures=data.response||[],numeric=new Map(registered.filter(x=>/^\d+$/.test(x.code)).map(x=>[Number(x.code),x])),matched=fixtures.filter((x:any)=>numeric.has(Number(x.league?.id)));
    if(response.ok&&!error&&!matched.length){const lr=await fetch("https://v3.football.api-sports.io/fixtures?live=all",{headers:{"x-apisports-key":apiKey},next:{revalidate:15}}),ld=await lr.json(),le=ld?.errors&&Object.keys(ld.errors).length?String(Object.values(ld.errors)[0]):"";if(lr.ok&&!le){response=lr;data=ld;fixtures=ld.response||[];matched=fixtures.filter((x:any)=>numeric.has(Number(x.league?.id)));}}
    if(response.ok&&!error&&matched.length){const games=matched.map((x:any)=>{const reg=numeric.get(Number(x.league?.id))!;return {provider:"api-football",id:x.fixture?.id,date:x.fixture?.date,minute:x.fixture?.status?.elapsed||0,status:x.fixture?.status?.short,statusLong:x.fixture?.status?.long,leagueId:x.league?.id,registeredLeagueId:reg.id,registeredLeagueName:reg.name,league:x.league?.name,country:x.league?.country,home:x.teams?.home?.name,away:x.teams?.away?.name,homeLogo:x.teams?.home?.logo,awayLogo:x.teams?.away?.logo,hg:x.goals?.home??0,ag:x.goals?.away??0}});return NextResponse.json({available:true,source:"API-Football",updatedAt:Date.now(),remaining:response.headers.get("x-ratelimit-requests-remaining"),games});}
    primaryReason=error||(!response.ok?"API-Football indisponível.":"A API-Football não retornou jogos das ligas vinculadas.");
  }catch{primaryReason="Falha ao consultar a API-Football.";}else primaryReason="API-Football não configurada.";
  if(!fdToken)return NextResponse.json({available:false,games:[],reason:`${primaryReason} Configure FOOTBALL_DATA_TOKEN para usar a alternativa gratuita.`});
  try{const r=await fetch(`https://api.football-data.org/v4/matches?dateFrom=${today}&dateTo=${today}`,{headers:{"X-Auth-Token":fdToken},next:{revalidate:60}}),d=await r.json();if(!r.ok)return NextResponse.json({available:false,games:[],reason:`Football-Data.org: ${d?.message||"token ou serviço indisponível."}`});const matches=d.matches||[],findLeague=(name:string)=>{const c=clean(name);return registered.find(x=>{const n=clean(x.name);return n===c||n.includes(c)||c.includes(n)});},games=matches.map((m:any)=>{const reg=findLeague(String(m.competition?.name||""));if(!reg)return null;const st=statusMap[m.status]||{short:m.status,long:m.status};return {provider:"football-data",id:m.id,date:m.utcDate,minute:0,status:st.short,statusLong:st.long,leagueId:m.competition?.id,registeredLeagueId:reg.id,registeredLeagueName:reg.name,league:m.competition?.name,country:m.area?.name||reg.country,home:m.homeTeam?.name,away:m.awayTeam?.name,homeLogo:m.homeTeam?.crest,awayLogo:m.awayTeam?.crest,hg:m.score?.fullTime?.home??m.score?.halfTime?.home??0,ag:m.score?.fullTime?.away??m.score?.halfTime?.away??0};}).filter(Boolean);return NextResponse.json({available:true,source:"Football-Data.org gratuito (placares podem ter atraso)",updatedAt:Date.now(),games,reason:games.length?"":`${primaryReason} O Football-Data.org não retornou hoje jogos das competições cadastradas.`});}catch{return NextResponse.json({available:false,games:[],reason:`${primaryReason} Também não foi possível consultar o Football-Data.org.`});}
}
