export type Game = {
  date?: string;
  round?: string;
  referee?: string;
  home: string;
  away: string;
  hg: number;
  ag: number;
  hc: number;
  ac: number;
  hy: number;
  ay: number;
  hr: number;
  ar: number;
  hs: number;
  as: number;
  hst: number;
  ast: number;
  hf?: number;
  af?: number;
  hxg?: number;
  axg?: number;
  hp?: number;
  ap?: number;
  homeGoalMinutes?: number[];
  awayGoalMinutes?: number[];
  homeCornerMinutes?: number[];
  awayCornerMinutes?: number[];
};
export type DataQuality = {
  goals: boolean;
  corners: boolean;
  cards: boolean;
  shots: boolean;
  shotsOnTarget: boolean;
  referees?: boolean;
  xg?: boolean;
  possession?: boolean;
};
export type League = {
  id: string;
  code: string;
  country: string;
  name: string;
  season: string;
  fileName?: string;
  updatedAt: number;
  games: Game[];
  quality?: DataQuality;
  qualityReport?: {score:number;grade:"Excelente"|"Boa"|"Regular"|"Baixa";totalGames:number;duplicates:number;datedGames:number;latestGameDate?:string;warnings:string[]};
  apiSync?: {
    updatedAt: number;
    status: string;
    error?: string;
    round?: string;
    remaining?: number | null;
    games: Game[];
  };
};
