import { NextResponse } from "next/server";
import { isAuthorized } from "@/lib/auth";
import { initDb, pool } from "@/lib/db";
const known:Record<string,number>={E0:39,E1:40,SP1:140,SP2:141,D1:78,D2:79,I1:135,I2:136,F1:61,F2:62,N1:88,P1:94,B1:144,BRA:71,ARG:128,USA:253};
const countries:Record<string,string>={Brasil:"Brazil",Inglaterra:"England",Espanha:"Spain",Alemanha:"Germany",Itália:"Italy",Italia:"Italy",França:"France",Holanda:"Netherlands",Portugal:"Portugal",Bélgica:"Belgium",Belgica:"Belgium",Argentina:"Argentina","Estados Unidos":"USA"};
const clean=(x:string)=>x.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
async function call(path:string,key:string,revalidate=900){const r=await fetch(`https://v3.football.api-sports.io/${path}`,{headers:{"x-apisports-key":key},next:{revalidate}}),data=await r.json();return {ok:r.ok,data,remaining:r.headers.get("x-ratelimit-requests-remaining")};}
export async function GET(req:Request){
 if(!(await isAuthorized()))return NextResponse.json({error:"Faça login para acessar."},{status:401});
 const id=new URL(req.url).searchParams.get("leagueId")||"",key=process.env.API_FOOTBALL_KEY;if(!key)return NextResponse.json({available:false,reason:"API-Football ainda não configurada."});
 await initDb();const {rows}=await pool.query("SELECT code,country,name FROM leagues WHERE id=$1 LIMIT 1",[id]),l=rows[0];if(!l)return NextResponse.json({available:false,reason:"Liga cadastrada não encontrada."});
 try{let apiLeague=known[String(l.code||"").toUpperCase()],season:number|undefined,apiName=String(l.name);const current=await call(`leagues?current=true&search=${encodeURIComponent(String(l.name))}`,key,21600),items=current.data?.response||[],country=countries[String(l.country)]||String(l.country),name=clean(String(l.name));const found=items.find((x:any)=>clean(String(x.country?.name||""))===clean(country)&&clean(String(x.league?.name||"")).includes(name))||items.find((x:any)=>clean(String(x.country?.name||""))===clean(country))||items[0];if(found){apiLeague=found.league?.id;apiName=found.league?.name||apiName;season=found.seasons?.find((s:any)=>s.current)?.year;}if(!apiLeague||!season)return NextResponse.json({available:false,reason:`A API não encontrou ${l.name} (${l.country}) na temporada atual. Confira o nome cadastrado.`});
 const result=await call(`standings?league=${apiLeague}&season=${season}`,key),table=result.data?.response?.[0]?.league?.standings?.[0];if(!result.ok||!Array.isArray(table))return NextResponse.json({available:false,reason:(result.data?.errors&&Object.values(result.data.errors)[0])||"A classificação atual ainda não foi disponibilizada pela API."});
 const norm=(part:"all"|"home"|"away")=>table.map((r:any)=>{const x=r[part]||{};return {team:r.team?.name,p:part==="all"?r.points:(x.win||0)*3+(x.draw||0),j:x.played||0,v:x.win||0,e:x.draw||0,d:x.lose||0,gp:x.goals?.for||0,gc:x.goals?.against||0,sg:(x.goals?.for||0)-(x.goals?.against||0),form:String(r.form||"").split("").slice(-5).map((f:string)=>f==="W"?"V":f==="D"?"E":"D")}}).sort((a:any,b:any)=>b.p-a.p||b.sg-a.sg||b.gp-a.gp);
 return NextResponse.json({available:true,source:"API-Football",updatedAt:Date.now(),league:{id:apiLeague,name:apiName,season},remaining:result.remaining,tables:{TOTAL:norm("all"),HOME:norm("home"),AWAY:norm("away")}});
 }catch{return NextResponse.json({available:false,reason:"Não foi possível consultar a classificação atual na API."});}
}
