import {NextResponse} from "next/server";
import {isAuthorized} from "@/lib/auth";
import {initDb,pool} from "@/lib/db";
const apiIds:Record<string,number>={E0:39,E1:40,SP1:140,SP2:141,D1:78,D2:79,I1:135,I2:136,F1:61,F2:62,N1:88,P1:94,B1:144,BRA:71,ARG:128,USA:253};
const fdCodes:Record<string,string>={E0:"PL",E1:"ELC",SP1:"PD",D1:"BL1",I1:"SA",F1:"FL1",N1:"DED",P1:"PPL",BRA:"BSA"};
const countries:Record<string,string>={Brasil:"Brazil",Inglaterra:"England",Espanha:"Spain",Alemanha:"Germany",Itália:"Italy",Italia:"Italy",França:"France",Holanda:"Netherlands",Portugal:"Portugal",Bélgica:"Belgium",Belgica:"Belgium",Argentina:"Argentina","Estados Unidos":"USA",EUA:"USA"};
const clean=(x:string)=>x.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
const currentLabel=(v:string)=>clean(v)==="atual"||clean(v)==="current";
const yearFrom=(v:string)=>{const m=v.match(/(?:19|20)\d{2}/);return m?Number(m[0]):undefined};
const tableRows=(table:any[]=[])=>table.map((r:any)=>({team:r.team?.name||"",crest:r.team?.crest||r.team?.logo||"",p:Number(r.points||0),j:Number(r.playedGames||r.all?.played||0),v:Number(r.won||r.all?.win||0),e:Number(r.draw||r.all?.draw||0),d:Number(r.lost||r.all?.lose||0),gp:Number(r.goalsFor||r.all?.goals?.for||0),gc:Number(r.goalsAgainst||r.all?.goals?.against||0),sg:Number(r.goalDifference??((r.goalsFor||0)-(r.goalsAgainst||0))),form:String(r.form||"").replace(/[^WDL]/g,"").split("").slice(-5).map((f:string)=>f==="W"?"V":f==="D"?"E":"D")}));
function fdCode(l:any){const saved=String(l.code||"").trim().toUpperCase();if(fdCodes[saved])return fdCodes[saved];const c=clean(String(l.country)),n=clean(String(l.name));if(c==="brasil"&&(n.includes("seriea")||n.includes("brasileirao"))&&!n.includes("serieb"))return "BSA";if(c==="inglaterra"&&n==="premierleague")return "PL";if(c==="inglaterra"&&n==="championship")return "ELC";if(c==="alemanha"&&n==="bundesliga")return "BL1";if(c==="espanha"&&(n==="laliga"||n==="primeradivision"))return "PD";if(c==="italia"&&n==="seriea")return "SA";if(c==="franca"&&n==="ligue1")return "FL1";if(c==="holanda"&&n==="eredivisie")return "DED";if(c==="portugal"&&n==="primeiraliga")return "PPL";return ""}
async function footballData(l:any,token:string){const code=fdCode(l);if(!code)return null;const r=await fetch(`https://api.football-data.org/v4/competitions/${code}/standings`,{headers:{"X-Auth-Token":token},next:{revalidate:900}}),d=await r.json();if(!r.ok)return {available:false,reason:d.message||"A classificação não foi liberada no plano gratuito."};const startYear=yearFrom(String(d.season?.startDate||"")),registered=String(l.season||""),wanted=yearFrom(registered);if(!currentLabel(registered)&&wanted!==startYear)return {available:false,reason:`A API oferece ${d.competition?.name||l.name} na temporada atual ${startYear}, mas a liga está cadastrada como ${registered}. Nenhuma temporada será misturada.`};const find=(type:string)=>d.standings?.find((s:any)=>s.type===type)?.table||[],total=find("TOTAL"),home=find("HOME"),away=find("AWAY");if(!total.length)return {available:false,reason:"A competição existe, mas ainda não possui tabela de classificação."};return {available:true,source:"Football-Data.org",updatedAt:Date.now(),league:{code,name:d.competition?.name||l.name,season:startYear,currentMatchday:d.season?.currentMatchday||null},tables:{TOTAL:tableRows(total),HOME:tableRows(home.length?home:total),AWAY:tableRows(away.length?away:total)}}}
async function apiFootball(l:any,key:string){const saved=String(l.code||"").trim().toUpperCase();let league=/^\d+$/.test(saved)?Number(saved):apiIds[saved],found:any;const call=async(path:string)=>{const r=await fetch(`https://v3.football.api-sports.io/${path}`,{headers:{"x-apisports-key":key},next:{revalidate:900}}),data=await r.json();return {r,data}};if(league){const q=await call(`leagues?id=${league}`);found=q.data?.response?.[0]}if(!found){const q=await call(`leagues?search=${encodeURIComponent(String(l.name))}`),country=countries[String(l.country)]||String(l.country),name=clean(String(l.name));found=(q.data?.response||[]).find((x:any)=>clean(String(x.country?.name||""))===clean(country)&&clean(String(x.league?.name||""))===name)}if(!found)return {available:false,reason:`A API não encontrou ${l.name} em ${l.country}. Associe o ID correto no Painel Admin.`};const registered=String(l.season||""),wanted=currentLabel(registered)?found.seasons?.find((s:any)=>s.current)?.year:yearFrom(registered),valid=found.seasons?.some((s:any)=>Number(s.year)===wanted);if(!wanted||!valid)return {available:false,reason:`A API não disponibiliza ${l.name} na temporada ${registered}. Nenhuma outra temporada será usada.`};league=found.league.id;const q=await call(`standings?league=${league}&season=${wanted}`),table=q.data?.response?.[0]?.league?.standings?.[0];if(!q.r.ok||!Array.isArray(table))return {available:false,reason:String(Object.values(q.data?.errors||{})[0]||"Classificação indisponível nesta API.")};const norm=(part:"all"|"home"|"away")=>table.map((r:any)=>{const x=r[part]||{};return {team:r.team?.name,crest:r.team?.logo||"",p:part==="all"?r.points:(x.win||0)*3+(x.draw||0),j:x.played||0,v:x.win||0,e:x.draw||0,d:x.lose||0,gp:x.goals?.for||0,gc:x.goals?.against||0,sg:(x.goals?.for||0)-(x.goals?.against||0),form:String(r.form||"").split("").slice(-5).map((f:string)=>f==="W"?"V":f==="D"?"E":"D")}}).sort((a:any,b:any)=>b.p-a.p||b.sg-a.sg||b.gp-a.gp);return {available:true,source:"API-Football",updatedAt:Date.now(),league:{id:league,name:found.league.name,season:wanted},tables:{TOTAL:norm("all"),HOME:norm("home"),AWAY:norm("away")}}}
export async function GET(req:Request){if(!await isAuthorized())return NextResponse.json({error:"Faça login para acessar."},{status:401});const id=new URL(req.url).searchParams.get("leagueId")||"";await initDb();const {rows}=await pool.query("SELECT code,country,name,season FROM leagues WHERE id=$1 LIMIT 1",[id]),l=rows[0];if(!l)return NextResponse.json({available:false,reason:"Liga cadastrada não encontrada."});try{const token=process.env.FOOTBALL_DATA_TOKEN;if(token){const fd=await footballData(l,token);if(fd?.available)return NextResponse.json(fd);if(fd&&fdCode(l))return NextResponse.json(fd)}const key=process.env.API_FOOTBALL_KEY;if(key)return NextResponse.json(await apiFootball(l,key));return NextResponse.json({available:false,reason:"Esta competição não está na cobertura gratuita configurada. Nenhuma tabela de outra temporada será usada."})}catch{return NextResponse.json({available:false,reason:"Não foi possível consultar a classificação agora. Tente novamente em alguns minutos."})}}
